[package]
name = "sparsers"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = {version = "0.17.2", features = ["rayon"]}
num-traits = "0.2.19"
rayon = "1.11.0"
thiserror = "2.0.18"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.8.2"
ndarray-npy = "0.10.0"

[[bench]]
name = "benchmark_sparsers"
harness = false