[package]
name = "sparsers"
version = "0.1.1"
edition = "2024"
authors = ["NewBornRustacean <huiseomkim@gmail.com>"]
description = "sparerse-rs: sparse matrix computation written in rust"
license = "MIT"
repository = "https://github.com/NewBornRustacean/sparsers"
homepage = "https://github.com/NewBornRustacean/sparsers"
documentation = "https://docs.rs/sparsers"
readme = "README.md"
keywords = ["sparse-matrix", "linear-algebra", "scientific-computing", "data-science"]
categories = ["algorithms", "data-structures", "science"]
rust-version = "1.92.0"

[dependencies]
ndarray = {version = "0.17.2", features = ["rayon"]}
num-traits = "0.2.19"
rayon = "1.11.0"
thiserror = "2.0.18"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.8.2"
ndarray-npy = "0.10.0"

[[bench]]
name = "benchmark_sparsers"
harness = false